name: CI for Lightning AI Model

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot

      - name: Run training
        run: |
          chmod +x * && python m.py  # Or whatever your script is
